<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'csrunner\\filter' => '/Filter.php',
                'csrunner\\filter\\blacklist' => '/Filter/Blacklist.php',
                'csrunner\\runner' => '/Runner.php',
                'csrunner\\scm' => '/Scm.php',
                'csrunner\\scm\\git' => '/Scm/Git.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd