<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'csrunner\\codesniffercommand\\command' => '/CodeSnifferCommand/Command.php',
                'csrunner\\command' => '/Command.php',
                'csrunner\\filefinder' => '/FileFinder.php',
                'csrunner\\filter' => '/Filter.php',
                'csrunner\\filter\\blacklist' => '/Filter/Blacklist.php',
                'csrunner\\finder' => '/Finder.php',
                'csrunner\\finder\\file' => '/Finder/File.php',
                'csrunner\\finder\\passthrough' => '/Finder/PassThrough.php',
                'csrunner\\lintcommand\\command' => '/LintCommand/Command.php',
                'csrunner\\lintcommand\\linter' => '/LintCommand/Linter.php',
                'csrunner\\lintcommand\\reporter' => '/LintCommand/Reporter.php',
                'csrunner\\runner' => '/Runner.php',
                'csrunner\\scm' => '/Scm.php',
                'csrunner\\scm\\git' => '/Scm/Git.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd